server:
  port: 8080

spring:
  application:
    name: elara-gateway

  cloud:
    gateway:
      routes:
        - id: elara-users
          uri: lb://elara-users
          predicates:
            - Path=/api/*/users/**

        - id: elara-login
          uri: lb://elara-login
          predicates:
            - Path=/api/*/auth/**

        - id: elara-products-get
          uri: lb://elara-products-get
          predicates:
            - Path=/api/*/products/**,/api/*/sports/**,/api/*/features/**,/api/*/colors/**
            - Method=GET

        - id: elara-orders
          uri: lb://elara-orders
          predicates:
            - Path=/api/*/orders/**

        - id: elara-admin-console
          uri: lb://elara-admin-console
          predicates:
            - Path=/api/*/admin-console/**

        - id: elara-delivery
          uri: lb://elara-delivery
          predicates:
            - Path=/api/*/delivery/**

        - id: elara-payment
          uri: lb://elara-payment
          predicates:
            - Path=/api/*/payment/**
